// Code generated by entc, DO NOT EDIT.

package card

const (
	// Label holds the string label denoting the card type in the database.
	Label = "card"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCardID holds the string denoting the cardid field in the database.
	FieldCardID = "card_id"

	// Table holds the table name of the card in the database.
	Table = "cards"
)

// Columns holds all SQL columns for card fields.
var Columns = []string{
	FieldID,
	FieldAmount,
	FieldCardID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
