// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: area.proto

package model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CircularService_Area_FullMethodName = "/model.CircularService/Area"
)

// CircularServiceClient is the client API for CircularService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义一个圆形服务
type CircularServiceClient interface {
	// 定义计算面积接口
	Area(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AreaRequest, AreaResponse], error)
}

type circularServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCircularServiceClient(cc grpc.ClientConnInterface) CircularServiceClient {
	return &circularServiceClient{cc}
}

func (c *circularServiceClient) Area(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AreaRequest, AreaResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CircularService_ServiceDesc.Streams[0], CircularService_Area_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AreaRequest, AreaResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CircularService_AreaClient = grpc.BidiStreamingClient[AreaRequest, AreaResponse]

// CircularServiceServer is the server API for CircularService service.
// All implementations must embed UnimplementedCircularServiceServer
// for forward compatibility.
//
// 定义一个圆形服务
type CircularServiceServer interface {
	// 定义计算面积接口
	Area(grpc.BidiStreamingServer[AreaRequest, AreaResponse]) error
	mustEmbedUnimplementedCircularServiceServer()
}

// UnimplementedCircularServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCircularServiceServer struct{}

func (UnimplementedCircularServiceServer) Area(grpc.BidiStreamingServer[AreaRequest, AreaResponse]) error {
	return status.Error(codes.Unimplemented, "method Area not implemented")
}
func (UnimplementedCircularServiceServer) mustEmbedUnimplementedCircularServiceServer() {}
func (UnimplementedCircularServiceServer) testEmbeddedByValue()                         {}

// UnsafeCircularServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CircularServiceServer will
// result in compilation errors.
type UnsafeCircularServiceServer interface {
	mustEmbedUnimplementedCircularServiceServer()
}

func RegisterCircularServiceServer(s grpc.ServiceRegistrar, srv CircularServiceServer) {
	// If the following call panics, it indicates UnimplementedCircularServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CircularService_ServiceDesc, srv)
}

func _CircularService_Area_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CircularServiceServer).Area(&grpc.GenericServerStream[AreaRequest, AreaResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CircularService_AreaServer = grpc.BidiStreamingServer[AreaRequest, AreaResponse]

// CircularService_ServiceDesc is the grpc.ServiceDesc for CircularService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CircularService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "model.CircularService",
	HandlerType: (*CircularServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Area",
			Handler:       _CircularService_Area_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "area.proto",
}
