// Code generated by entc, DO NOT EDIT.

package admin

import (
	"fmt"
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the admin type in the database.
	Label = "admin"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAge holds the string denoting the age field in the database.
	FieldAge = "age"
	// FieldRank holds the string denoting the rank field in the database.
	FieldRank = "rank"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldStrings holds the string denoting the strings field in the database.
	FieldStrings = "strings"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"

	// Table holds the table name of the admin in the database.
	Table = "admins"
)

// Columns holds all SQL columns for admin fields.
var Columns = []string{
	FieldID,
	FieldAge,
	FieldRank,
	FieldActive,
	FieldName,
	FieldCreatedAt,
	FieldURL,
	FieldStrings,
	FieldState,
	FieldUUID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AgeValidator is a validator for the "age" field. It is called by the builders before save.
	AgeValidator func(int) error
	// DefaultActive holds the default value on creation for the active field.
	DefaultActive bool
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
	// DefaultUUID holds the default value on creation for the uuid field.
	DefaultUUID func() uuid.UUID
)

// State defines the type for the state enum field.
type State string

// State values.
const (
	StateOn  State = "on"
	StateOff State = "off"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateOn, StateOff:
		return nil
	default:
		return fmt.Errorf("admin: invalid enum value for state field: %q", s)
	}
}
