// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"io"
)

// Injectors from wire.go:

func injectCtx() context.Context {
	contextContext := providerCtx()
	return contextContext
}

func injectWirter() io.Writer {
	writer := provideWriter()
	return writer
}

func injectMessages() []Message {
	v := GoodMessages()
	return v
}

func injectGreeter() *Greeter {
	contextContext := providerCtx()
	v := GoodMessages()
	writer := provideWriter()
	options := &Options{
		Message: v,
		Writer:  writer,
	}
	greeter := NewGreeter(contextContext, options)
	return greeter
}
