// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func injectFooBarPointer() *FooBar {
	foo := ProvideFoo()
	bar := ProvideBar()
	fooBar := &FooBar{
		MyFoo: foo,
		MyBar: bar,
	}
	return fooBar
}

func injectFooBar() FooBar {
	foo := ProvideFoo()
	bar := ProvideBar()
	fooBar := FooBar{
		MyFoo: foo,
		MyBar: bar,
	}
	return fooBar
}

func injectFooBarOfFoo() Foo {
	fooBar := provoideFooBar()
	foo := fooBar.MyFoo
	return foo
}
