pid:
	cc pid.c -o pid.app && ./pid.app
fork:
	cc fork.c -o fork.app && ./fork.app
forkfull:
	cc fork.c -o fork.app && ./fork.app > fork.log
wait:
	cc wait.c -o wait.app && ./wait.app
son:
	cc son.c -o son.app && ./son.app
tellwait:
	cc tellwait.c -o tellwait.app && ./tellwait.app
echoall:
	cc echoall.c -o echoall.app && ./echoall.app
exec:
	cc exec.c -o exec.app && ./exec.app
echoarg:
	cc echoarg.c -o echoarg.app && ./echoarg.app
interp:
	cc interp.c -o interp.app && ./interp.app
system:
	cc system.c -o system.app && ./system.app
nice:
	cc nice.c -o nice.app && ./nice.app