exit:
	cc exit.c -o exit.app && ./exit.app
hello:
	cc hello.c -std=c99 -o hello.app && ./hello.app
atexit:
	cc atexit.c -std=c99 -o atexit.app && ./atexit.app
echo:
	cc echo.c  -o echo.app && ./echo.app dd ff aa
environ:
	cc environ.c  -o environ.app && ./environ.app
malloc:
	cc malloc.c  -o malloc.app && ./malloc.app
env:
	cc env.c  -o env.app && ./env.app
line:
	cc line.c  -o line.app && ./line.app
valjump:
	cc valjump.c  -o valjump.app && ./valjump.app
rlimit:
	cc rlimit.c  -o rlimit.app && ./rlimit.app
clean:
	rm *.app