// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"os"
)

// Injectors from wire.go:

func injectFile() (*os.File, func(), error) {
	file, cleanup, err := provideFile()
	if err != nil {
		return nil, nil, err
	}
	return file, func() {
		cleanup()
	}, nil
}
