// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
	"os"
)

// Injectors from wire.go:

func NewFile(path Path) (*os.File, func(), error) {
	file, cleanup, err := provideFile(path)
	if err != nil {
		return nil, nil, err
	}
	return file, func() {
		cleanup()
	}, nil
}

// wire.go:

type Path string

func provideFile(path Path) (*os.File, func(), error) {
	f, err := os.Open(string(path))
	if err != nil {
		return nil, nil, err
	}
	cleanup := func() {
		if err := f.Close(); err != nil {
			fmt.Println("close")
		}
	}
	return f, cleanup, nil
}
