// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/area.proto

package normal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CircularService_Area_FullMethodName = "/model.CircularService/Area"
)

// CircularServiceClient is the client API for CircularService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义一个圆形服务
type CircularServiceClient interface {
	// 定义计算面积接口
	Area(ctx context.Context, in *AreaRequest, opts ...grpc.CallOption) (*AreaResponse, error)
}

type circularServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCircularServiceClient(cc grpc.ClientConnInterface) CircularServiceClient {
	return &circularServiceClient{cc}
}

func (c *circularServiceClient) Area(ctx context.Context, in *AreaRequest, opts ...grpc.CallOption) (*AreaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AreaResponse)
	err := c.cc.Invoke(ctx, CircularService_Area_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CircularServiceServer is the server API for CircularService service.
// All implementations must embed UnimplementedCircularServiceServer
// for forward compatibility.
//
// 定义一个圆形服务
type CircularServiceServer interface {
	// 定义计算面积接口
	Area(context.Context, *AreaRequest) (*AreaResponse, error)
	mustEmbedUnimplementedCircularServiceServer()
}

// UnimplementedCircularServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCircularServiceServer struct{}

func (UnimplementedCircularServiceServer) Area(context.Context, *AreaRequest) (*AreaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Area not implemented")
}
func (UnimplementedCircularServiceServer) mustEmbedUnimplementedCircularServiceServer() {}
func (UnimplementedCircularServiceServer) testEmbeddedByValue()                         {}

// UnsafeCircularServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CircularServiceServer will
// result in compilation errors.
type UnsafeCircularServiceServer interface {
	mustEmbedUnimplementedCircularServiceServer()
}

func RegisterCircularServiceServer(s grpc.ServiceRegistrar, srv CircularServiceServer) {
	// If the following call panics, it indicates UnimplementedCircularServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CircularService_ServiceDesc, srv)
}

func _CircularService_Area_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AreaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CircularServiceServer).Area(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CircularService_Area_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CircularServiceServer).Area(ctx, req.(*AreaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CircularService_ServiceDesc is the grpc.ServiceDesc for CircularService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CircularService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "model.CircularService",
	HandlerType: (*CircularServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Area",
			Handler:    _CircularService_Area_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/area.proto",
}
