// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/area.proto

package normal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义一个点
type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_proto_area_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_proto_area_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_proto_area_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 定义圆
type Circular struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dot           *Point                 `protobuf:"bytes,1,opt,name=dot,proto3" json:"dot,omitempty"`
	Radius        float64                `protobuf:"fixed64,2,opt,name=radius,proto3" json:"radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Circular) Reset() {
	*x = Circular{}
	mi := &file_proto_area_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Circular) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Circular) ProtoMessage() {}

func (x *Circular) ProtoReflect() protoreflect.Message {
	mi := &file_proto_area_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Circular.ProtoReflect.Descriptor instead.
func (*Circular) Descriptor() ([]byte, []int) {
	return file_proto_area_proto_rawDescGZIP(), []int{1}
}

func (x *Circular) GetDot() *Point {
	if x != nil {
		return x.Dot
	}
	return nil
}

func (x *Circular) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

// 定义请求消息
type AreaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Circular      *Circular              `protobuf:"bytes,2,opt,name=circular,proto3" json:"circular,omitempty"`
	Color         *wrapperspb.Int64Value `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AreaRequest) Reset() {
	*x = AreaRequest{}
	mi := &file_proto_area_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaRequest) ProtoMessage() {}

func (x *AreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_area_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaRequest.ProtoReflect.Descriptor instead.
func (*AreaRequest) Descriptor() ([]byte, []int) {
	return file_proto_area_proto_rawDescGZIP(), []int{2}
}

func (x *AreaRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AreaRequest) GetCircular() *Circular {
	if x != nil {
		return x.Circular
	}
	return nil
}

func (x *AreaRequest) GetColor() *wrapperspb.Int64Value {
	if x != nil {
		return x.Color
	}
	return nil
}

// 定义响应消息
type AreaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Area          float64                `protobuf:"fixed64,2,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AreaResponse) Reset() {
	*x = AreaResponse{}
	mi := &file_proto_area_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AreaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaResponse) ProtoMessage() {}

func (x *AreaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_area_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaResponse.ProtoReflect.Descriptor instead.
func (*AreaResponse) Descriptor() ([]byte, []int) {
	return file_proto_area_proto_rawDescGZIP(), []int{3}
}

func (x *AreaResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AreaResponse) GetArea() float64 {
	if x != nil {
		return x.Area
	}
	return 0
}

var File_proto_area_proto protoreflect.FileDescriptor

const file_proto_area_proto_rawDesc = "" +
	"\n" +
	"\x10proto/area.proto\x12\x05model\x1a\x1egoogle/protobuf/wrappers.proto\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"B\n" +
	"\bCircular\x12\x1e\n" +
	"\x03dot\x18\x01 \x01(\v2\f.model.PointR\x03dot\x12\x16\n" +
	"\x06radius\x18\x02 \x01(\x01R\x06radius\"\x8b\x01\n" +
	"\vAreaRequest\x12\x1c\n" +
	"\trequestId\x18\x01 \x01(\tR\trequestId\x12+\n" +
	"\bcircular\x18\x02 \x01(\v2\x0f.model.CircularR\bcircular\x121\n" +
	"\x05color\x18\x03 \x01(\v2\x1b.google.protobuf.Int64ValueR\x05color\"6\n" +
	"\fAreaResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x12\n" +
	"\x04area\x18\x02 \x01(\x01R\x04area2D\n" +
	"\x0fCircularService\x121\n" +
	"\x04Area\x12\x12.model.AreaRequest\x1a\x13.model.AreaResponse\"\x00B6Z4github.com/hanzhuoxian/study/go/examples/grpc/normalb\x06proto3"

var (
	file_proto_area_proto_rawDescOnce sync.Once
	file_proto_area_proto_rawDescData []byte
)

func file_proto_area_proto_rawDescGZIP() []byte {
	file_proto_area_proto_rawDescOnce.Do(func() {
		file_proto_area_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_area_proto_rawDesc), len(file_proto_area_proto_rawDesc)))
	})
	return file_proto_area_proto_rawDescData
}

var file_proto_area_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_area_proto_goTypes = []any{
	(*Point)(nil),                 // 0: model.Point
	(*Circular)(nil),              // 1: model.Circular
	(*AreaRequest)(nil),           // 2: model.AreaRequest
	(*AreaResponse)(nil),          // 3: model.AreaResponse
	(*wrapperspb.Int64Value)(nil), // 4: google.protobuf.Int64Value
}
var file_proto_area_proto_depIdxs = []int32{
	0, // 0: model.Circular.dot:type_name -> model.Point
	1, // 1: model.AreaRequest.circular:type_name -> model.Circular
	4, // 2: model.AreaRequest.color:type_name -> google.protobuf.Int64Value
	2, // 3: model.CircularService.Area:input_type -> model.AreaRequest
	3, // 4: model.CircularService.Area:output_type -> model.AreaResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_area_proto_init() }
func file_proto_area_proto_init() {
	if File_proto_area_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_area_proto_rawDesc), len(file_proto_area_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_area_proto_goTypes,
		DependencyIndexes: file_proto_area_proto_depIdxs,
		MessageInfos:      file_proto_area_proto_msgTypes,
	}.Build()
	File_proto_area_proto = out.File
	file_proto_area_proto_goTypes = nil
	file_proto_area_proto_depIdxs = nil
}
