// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func injectMessage() string {
	foo := ProvideFoo()
	string2 := getS(foo)
	return string2
}

func injectField() string {
	foo := ProvideFoo()
	string2 := foo.S
	return string2
}

func injectBar() Bar {
	foo := ProvideFoo()
	bar := foo.Bar
	return bar
}

// wire.go:

type Foo struct {
	S   string
	N   int
	F   float64
	Bar Bar
}

type Bar struct {
	S string
}

func getS(foo Foo) string {
	return foo.S
}

func ProvideFoo() Foo {
	return Foo{
		S: "Hello",
		N: 88,
		F: 3.14,
		Bar: Bar{
			S: "Bar",
		},
	}
}
