// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func initializeFooBar() (FooBar, error) {
	foo := ProvideFoo()
	bar := ProvideBar()
	fooBar := FooBar{
		MyFoo: foo,
		MyBar: bar,
	}
	return fooBar, nil
}

func initializeFooOnly() (FooOnly, error) {
	foo := ProvideFoo()
	fooOnly := FooOnly{
		MyFoo: foo,
	}
	return fooOnly, nil
}

func initializeFooBarAll() (FooBarAll, error) {
	foo := ProvideFoo()
	bar := ProvideBar()
	fooBarAll := FooBarAll{
		MyFoo: foo,
		MyBar: bar,
	}
	return fooBarAll, nil
}

func initializeFooBarAllPointer() (*FooBarAll, error) {
	foo := ProvideFoo()
	bar := ProvideBar()
	fooBarAll := &FooBarAll{
		MyFoo: foo,
		MyBar: bar,
	}
	return fooBarAll, nil
}

func initializeFooIngore() (FooIngore, error) {
	foo := ProvideFoo()
	fooIngore := FooIngore{
		MyFoo: foo,
	}
	return fooIngore, nil
}
