// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/daymenu/gostudy/examples/ent/ent/admin"
	"github.com/daymenu/gostudy/examples/ent/ent/group"
	"github.com/daymenu/gostudy/examples/ent/ent/pet"
	"github.com/daymenu/gostudy/examples/ent/ent/schema"
	"github.com/daymenu/gostudy/examples/ent/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminFields := schema.Admin{}.Fields()
	_ = adminFields
	// adminDescAge is the schema descriptor for age field.
	adminDescAge := adminFields[0].Descriptor()
	// admin.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	admin.AgeValidator = adminDescAge.Validators[0].(func(int) error)
	// adminDescActive is the schema descriptor for active field.
	adminDescActive := adminFields[2].Descriptor()
	// admin.DefaultActive holds the default value on creation for the active field.
	admin.DefaultActive = adminDescActive.Default.(bool)
	// adminDescCreatedAt is the schema descriptor for created_at field.
	adminDescCreatedAt := adminFields[4].Descriptor()
	// admin.DefaultCreatedAt holds the default value on creation for the created_at field.
	admin.DefaultCreatedAt = adminDescCreatedAt.Default.(func() time.Time)
	// adminDescUUID is the schema descriptor for uuid field.
	adminDescUUID := adminFields[8].Descriptor()
	// admin.DefaultUUID holds the default value on creation for the uuid field.
	admin.DefaultUUID = adminDescUUID.Default.(func() uuid.UUID)
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[0].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = func() func(string) error {
		validators := groupDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	petMixin := schema.Pet{}.Mixin()
	petMixinFields0 := petMixin[0].Fields()
	petMixinFields1 := petMixin[1].Fields()
	petFields := schema.Pet{}.Fields()
	_ = petFields
	// petDescCreateTime is the schema descriptor for create_time field.
	petDescCreateTime := petMixinFields0[0].Descriptor()
	// pet.DefaultCreateTime holds the default value on creation for the create_time field.
	pet.DefaultCreateTime = petDescCreateTime.Default.(func() time.Time)
	// petDescUpdateTime is the schema descriptor for update_time field.
	petDescUpdateTime := petMixinFields0[1].Descriptor()
	// pet.DefaultUpdateTime holds the default value on creation for the update_time field.
	pet.DefaultUpdateTime = petDescUpdateTime.Default.(func() time.Time)
	// pet.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	pet.UpdateDefaultUpdateTime = petDescUpdateTime.UpdateDefault.(func() time.Time)
	// petDescStatus is the schema descriptor for status field.
	petDescStatus := petMixinFields1[0].Descriptor()
	// pet.DefaultStatus holds the default value on creation for the status field.
	pet.DefaultStatus = petDescStatus.Default.(int)
	// petDescName is the schema descriptor for name field.
	petDescName := petFields[0].Descriptor()
	// pet.DefaultName holds the default value on creation for the name field.
	pet.DefaultName = petDescName.Default.(string)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	userMixinFields1 := userMixin[1].Fields()
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userMixinFields0[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userMixinFields0[1].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userMixinFields1[0].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(int)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.DefaultEmail holds the default value on creation for the email field.
	user.DefaultEmail = userDescEmail.Default.(string)
}
