clean:
	rm -rf *.app *.txt
create:
	cc create.c -o create.app && ./create.app && rm -rf create.app
close:
	cc close.c -o close.app && ./close.app && rm -rf close.app
lseek:
	cc lseek.c -o lseek.app && ./lseek.app && rm -rf lseek.app
read:
	cc read.c -o read.app && ./read.app && rm -rf read.app
write:
	cc write.c -o write.app && ./write.app && rm -rf write.app
dup:
	cc dup.c -o dup.app && ./dup.app && rm -rf dup.app
fcntl:
	cc fcntl.c -o fcntl.app && ./fcntl.app close.c && rm -rf fcntl.app