// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
)

// Injectors from injector.go:

func initializeBaz(contextContext context.Context) (Baz, error) {
	foo := ProvideFoo()
	bar := ProvideBar(foo)
	baz, err := ProvideBaz(contextContext, bar)
	if err != nil {
		return Baz{}, err
	}
	return baz, nil
}

func initializeOther(contextContext context.Context) (Other, error) {
	foo := ProvideFoo()
	bar := ProvideBar(foo)
	baz, err := ProvideBaz(contextContext, bar)
	if err != nil {
		return Other{}, err
	}
	other := ProvideOther(baz)
	return other, nil
}
