fwide:
	cc fwide.c -o fwide.app && ./fwide.app
fopen:
	cc fopen.c -o fopen.app && ./fopen.app
io:
	cc io.c -o io.app && ./io.app
getc:
	cc getc.c -o getc.app && ./getc.app
putc:
	cc putc.c -o putc.app && ./putc.app
ferror:
	cc ferror.c -o ferror.app && ./ferror.app
getchar:
	cc getchar.c -o getchar.app && ./getchar.app
binio:
	cc binio.c -o binio.app && ./binio.app
pos:
	cc pos.c -o pos.app && ./pos.app
fgetpos:
	cc fgetpos.c -o fgetpos.app && ./fgetpos.app
printf:
	cc printf.c -o printf.app && ./printf.app
buffer:
	cc buffer.c -o buffer.app && ./buffer.app </etc/group
clean:
	rm *.app