// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vessel/vessel.proto

package daymenu_shipping_srv_vessel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vessel struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity             int64    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int64    `protobuf:"varint,3,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Long                 int64    `protobuf:"varint,5,opt,name=long,proto3" json:"long,omitempty"`
	Width                int64    `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Height               int64    `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	Status               int64    `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	OwnerId              string   `protobuf:"bytes,9,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vessel) Reset()         { *m = Vessel{} }
func (m *Vessel) String() string { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()    {}
func (*Vessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ef66862bb50716, []int{0}
}

func (m *Vessel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vessel.Unmarshal(m, b)
}
func (m *Vessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vessel.Marshal(b, m, deterministic)
}
func (m *Vessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vessel.Merge(m, src)
}
func (m *Vessel) XXX_Size() int {
	return xxx_messageInfo_Vessel.Size(m)
}
func (m *Vessel) XXX_DiscardUnknown() {
	xxx_messageInfo_Vessel.DiscardUnknown(m)
}

var xxx_messageInfo_Vessel proto.InternalMessageInfo

func (m *Vessel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Vessel) GetCapacity() int64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int64 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vessel) GetLong() int64 {
	if m != nil {
		return m.Long
	}
	return 0
}

func (m *Vessel) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Vessel) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Vessel) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Vessel) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

type Request struct {
	Page                 int64    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Search               string   `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Id                   int64    `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	GoodWeight           int64    `protobuf:"varint,5,opt,name=good_weight,json=goodWeight,proto3" json:"good_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ef66862bb50716, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Request) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Request) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

func (m *Request) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetGoodWeight() int64 {
	if m != nil {
		return m.GoodWeight
	}
	return 0
}

type Reponse struct {
	Vessel               *Vessel   `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
	Vessels              []*Vessel `protobuf:"bytes,2,rep,name=vessels,proto3" json:"vessels,omitempty"`
	Count                int64     `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Code                 int64     `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Reponse) Reset()         { *m = Reponse{} }
func (m *Reponse) String() string { return proto.CompactTextString(m) }
func (*Reponse) ProtoMessage()    {}
func (*Reponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04ef66862bb50716, []int{2}
}

func (m *Reponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reponse.Unmarshal(m, b)
}
func (m *Reponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reponse.Marshal(b, m, deterministic)
}
func (m *Reponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reponse.Merge(m, src)
}
func (m *Reponse) XXX_Size() int {
	return xxx_messageInfo_Reponse.Size(m)
}
func (m *Reponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Reponse.DiscardUnknown(m)
}

var xxx_messageInfo_Reponse proto.InternalMessageInfo

func (m *Reponse) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func (m *Reponse) GetVessels() []*Vessel {
	if m != nil {
		return m.Vessels
	}
	return nil
}

func (m *Reponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Reponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*Vessel)(nil), "daymenu.shipping.srv.vessel.Vessel")
	proto.RegisterType((*Request)(nil), "daymenu.shipping.srv.vessel.Request")
	proto.RegisterType((*Reponse)(nil), "daymenu.shipping.srv.vessel.Reponse")
}

func init() { proto.RegisterFile("proto/vessel/vessel.proto", fileDescriptor_04ef66862bb50716) }

var fileDescriptor_04ef66862bb50716 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0x25, 0x9b, 0x6d, 0x76, 0x77, 0xaa, 0x72, 0xb0, 0x10, 0x72, 0x8b, 0x10, 0xab, 0x85, 0x43,
	0x4f, 0x41, 0x2a, 0x47, 0xc4, 0x01, 0x21, 0x81, 0xb8, 0xa1, 0x2c, 0x85, 0x13, 0xaa, 0xdc, 0x78,
	0x94, 0x58, 0x4a, 0xec, 0x10, 0x3b, 0xd9, 0x96, 0x23, 0x3f, 0xc4, 0x67, 0xf0, 0x13, 0x7c, 0x0c,
	0xf2, 0xd8, 0xe9, 0xb1, 0xdd, 0xc3, 0x9e, 0x3c, 0xef, 0x65, 0xe6, 0xd9, 0xef, 0xd9, 0x0a, 0x9c,
	0x76, 0xbd, 0x71, 0xe6, 0xf5, 0x88, 0xd6, 0x62, 0x13, 0x97, 0x9c, 0x38, 0xf6, 0x4c, 0x8a, 0xdb,
	0x16, 0xf5, 0x90, 0xdb, 0x5a, 0x75, 0x9d, 0xd2, 0x55, 0x6e, 0xfb, 0x31, 0x0f, 0x2d, 0x9b, 0x7f,
	0x09, 0x64, 0xdf, 0xa8, 0x64, 0x8f, 0x61, 0xa6, 0x24, 0x4f, 0xd6, 0xc9, 0x79, 0x5a, 0xcc, 0x94,
	0x64, 0x67, 0xb0, 0x2c, 0x45, 0x27, 0x4a, 0xe5, 0x6e, 0xf9, 0x8c, 0xd8, 0x3b, 0xcc, 0x9e, 0x03,
	0xb4, 0xe2, 0xe6, 0x6a, 0x87, 0xaa, 0xaa, 0x1d, 0x4f, 0xe9, 0xeb, 0xaa, 0x15, 0x37, 0xdf, 0x89,
	0x60, 0x0c, 0xe6, 0x5a, 0xb4, 0xc8, 0xe7, 0xeb, 0xe4, 0x7c, 0x55, 0x50, 0xed, 0xb9, 0xc6, 0xe8,
	0x8a, 0x1f, 0x51, 0x33, 0xd5, 0xec, 0x09, 0x1c, 0xed, 0x94, 0x74, 0x35, 0xcf, 0x88, 0x0c, 0x80,
	0x3d, 0x85, 0xac, 0x0e, 0xc2, 0x0b, 0xa2, 0x23, 0xf2, 0xbc, 0x75, 0xc2, 0x0d, 0x96, 0x2f, 0x03,
	0x1f, 0x10, 0x3b, 0x85, 0xa5, 0xd9, 0x69, 0xec, 0xaf, 0x94, 0xe4, 0x2b, 0xda, 0x71, 0x41, 0xf8,
	0xb3, 0xdc, 0xfc, 0x4e, 0x60, 0x51, 0xe0, 0xcf, 0x01, 0x2d, 0x1d, 0xaa, 0x13, 0x15, 0x46, 0x87,
	0x54, 0x7b, 0x8f, 0x7e, 0xdd, 0xaa, 0x5f, 0x38, 0x79, 0x9c, 0x30, 0x6d, 0x87, 0xa2, 0x2f, 0x6b,
	0xf2, 0xb7, 0x2a, 0x22, 0x8a, 0x39, 0xcd, 0xef, 0x72, 0x7a, 0x01, 0xc7, 0x95, 0x31, 0x72, 0x0a,
	0x23, 0xf8, 0x03, 0x4f, 0x85, 0x34, 0x36, 0x7f, 0xe8, 0x10, 0x9d, 0xd1, 0x16, 0xd9, 0x5b, 0xc8,
	0x42, 0xf2, 0x74, 0x8c, 0xe3, 0x8b, 0x97, 0xf9, 0x3d, 0xb7, 0x93, 0x87, 0x9b, 0x29, 0xe2, 0x08,
	0x7b, 0x07, 0x8b, 0x50, 0x59, 0x3e, 0x5b, 0xa7, 0xfb, 0x4e, 0x4f, 0x33, 0x3e, 0xed, 0xd2, 0x0c,
	0x7a, 0xba, 0xaf, 0x00, 0x7c, 0x2c, 0xa5, 0x91, 0x18, 0x0d, 0x51, 0x7d, 0xf1, 0x37, 0x85, 0x93,
	0x30, 0xbd, 0xc5, 0x7e, 0x54, 0x25, 0xb2, 0x4b, 0xc8, 0x3e, 0xf4, 0x28, 0x1c, 0xb2, 0x7d, 0xf6,
	0x3c, 0x7b, 0x75, 0x6f, 0x53, 0x0c, 0x63, 0xf3, 0xc8, 0xcb, 0x5e, 0x76, 0xf2, 0xe0, 0xb2, 0x5b,
	0x48, 0x3f, 0xa1, 0x63, 0x0f, 0xb5, 0xd3, 0xbb, 0xd8, 0x5b, 0xf4, 0x2b, 0xcc, 0xbf, 0xf8, 0x37,
	0x73, 0x58, 0xd5, 0x1f, 0x70, 0xf2, 0x51, 0x69, 0xf9, 0x7e, 0x14, 0x8d, 0x12, 0xd7, 0xcd, 0x81,
	0xe5, 0xaf, 0x33, 0xfa, 0x07, 0xbc, 0xf9, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xea, 0x8d, 0xe0, 0x96,
	0x20, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for VesselService service

type VesselServiceClient interface {
	Create(ctx context.Context, in *Vessel, opts ...client.CallOption) (*Reponse, error)
	Update(ctx context.Context, in *Vessel, opts ...client.CallOption) (*Reponse, error)
	Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Reponse, error)
	Page(ctx context.Context, in *Request, opts ...client.CallOption) (*Reponse, error)
	FindAvaliable(ctx context.Context, in *Request, opts ...client.CallOption) (*Reponse, error)
}

type vesselServiceClient struct {
	c           client.Client
	serviceName string
}

func NewVesselServiceClient(serviceName string, c client.Client) VesselServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "daymenu.shipping.srv.vessel"
	}
	return &vesselServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *vesselServiceClient) Create(ctx context.Context, in *Vessel, opts ...client.CallOption) (*Reponse, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.Create", in)
	out := new(Reponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vesselServiceClient) Update(ctx context.Context, in *Vessel, opts ...client.CallOption) (*Reponse, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.Update", in)
	out := new(Reponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vesselServiceClient) Get(ctx context.Context, in *Request, opts ...client.CallOption) (*Reponse, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.Get", in)
	out := new(Reponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vesselServiceClient) Page(ctx context.Context, in *Request, opts ...client.CallOption) (*Reponse, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.Page", in)
	out := new(Reponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vesselServiceClient) FindAvaliable(ctx context.Context, in *Request, opts ...client.CallOption) (*Reponse, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.FindAvaliable", in)
	out := new(Reponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VesselService service

type VesselServiceHandler interface {
	Create(context.Context, *Vessel, *Reponse) error
	Update(context.Context, *Vessel, *Reponse) error
	Get(context.Context, *Request, *Reponse) error
	Page(context.Context, *Request, *Reponse) error
	FindAvaliable(context.Context, *Request, *Reponse) error
}

func RegisterVesselServiceHandler(s server.Server, hdlr VesselServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&VesselService{hdlr}, opts...))
}

type VesselService struct {
	VesselServiceHandler
}

func (h *VesselService) Create(ctx context.Context, in *Vessel, out *Reponse) error {
	return h.VesselServiceHandler.Create(ctx, in, out)
}

func (h *VesselService) Update(ctx context.Context, in *Vessel, out *Reponse) error {
	return h.VesselServiceHandler.Update(ctx, in, out)
}

func (h *VesselService) Get(ctx context.Context, in *Request, out *Reponse) error {
	return h.VesselServiceHandler.Get(ctx, in, out)
}

func (h *VesselService) Page(ctx context.Context, in *Request, out *Reponse) error {
	return h.VesselServiceHandler.Page(ctx, in, out)
}

func (h *VesselService) FindAvaliable(ctx context.Context, in *Request, out *Reponse) error {
	return h.VesselServiceHandler.FindAvaliable(ctx, in, out)
}
